const tasks=[['study1','学习 2 小时','📚','专注时光'],['study2','学习 2 小时','✍️','进阶练习'],['study3','学习 2 小时','🧠','知识沉淀'],['workout','健身 1.5 小时','🏃','保持活力'],['piano','练琴','🎹','音乐时刻']];
const $=id=>document.getElementById(id),key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;let sb,user,records={},selected=new Date(),month=new Date();selected.setHours(0,0,0,0);month=new Date(selected.getFullYear(),selected.getMonth(),1);
const rec=()=>records[key(selected)]||{checked:{},note:'',photos:[]};const done=r=>r&&Object.values(r.checked||{}).filter(Boolean).length===5;
function calendar(){let g=$('calendarGrid');g.innerHTML='';$('monthLabel').textContent=`${month.getFullYear()}年 ${month.getMonth()+1}月`;let first=new Date(month.getFullYear(),month.getMonth(),1),b=(first.getDay()+6)%7,last=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let i=0;i<b;i++)g.innerHTML+='<span class="day blank"></span>';for(let n=1;n<=last;n++){let d=new Date(month.getFullYear(),month.getMonth(),n),el=document.createElement('button');el.className='day';el.textContent=n;if(key(d)===key(selected))el.classList.add('chosen');if(done(records[key(d)]))el.innerHTML+= '<i class="done-dot"></i>';el.onclick=()=>{selected=d;render()};g.append(el)}}
function render(){let r=rec(),n=Object.values(r.checked||{}).filter(Boolean).length,p=Math.round(n/5*100);$('dateLabel').textContent=`${selected.getFullYear()}年${selected.getMonth()+1}月${selected.getDate()}日`;$('progressText').textContent=p+'%';$('progressRing').style.setProperty('--p',p);$('taskList').innerHTML=tasks.map(t=>`<div class="task ${r.checked[t[0]]?'checked':''}" data-id="${t[0]}"><span class="task-check">✓</span><span class="task-icon">${t[2]}</span><span class="task-text">${t[1]}</span><span class="task-tag">${t[3]}</span></div>`).join('');document.querySelectorAll('.task').forEach(x=>x.onclick=async()=>{let r=rec();r.checked[x.dataset.id]=!r.checked[x.dataset.id];await save(r);render()});$('noteInput').value=r.note||'';$('photoList').innerHTML=(r.photos||[]).map((p,i)=>`<div class="photo-thumb"><img src="${p}"><button class="remove-photo" data-i="${i}">×</button></div>`).join('');document.querySelectorAll('.remove-photo').forEach(x=>x.onclick=async()=>{let r=rec(),url=r.photos.splice(+x.dataset.i,1)[0],path=url.split('/daily-photos/')[1];await sb.storage.from('daily-photos').remove([path]);await save(r);render()});calendar()}
async function save(r){records[key(selected)]=r;let {error}=await sb.from('daily_records').upsert({user_id:user.id,record_date:key(selected),checked:r.checked,note:r.note,photos:r.photos},{onConflict:'user_id,record_date'});if(error)return alert(error.message);$('saveStatus').textContent='已保存';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
async function upload(files){for(let f of files){if(!f.type.startsWith('image/'))continue;let path=`${user.id}/${key(selected)}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,{error}=await sb.storage.from('daily-photos').upload(path,f);if(error)return alert(error.message);let {data}=sb.storage.from('daily-photos').getPublicUrl(path),r=rec();r.photos.push(data.publicUrl);await save(r)}render()}
async function start(){if(!window.SUPABASE_URL||window.SUPABASE_URL.includes('YOUR_')){$('authError').textContent='请先在 config.js 中填入 Supabase 配置。';return}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);let {data:{session}}=await sb.auth.getSession();if(session)await login(session.user)}async function login(u){user=u;$('authScreen').classList.add('hidden');let {data,error}=await sb.from('daily_records').select('*').eq('user_id',u.id);if(error)return alert(error.message);records=Object.fromEntries(data.map(x=>[x.record_date,{checked:x.checked,note:x.note,photos:x.photos}]));render()}
$('authForm').onsubmit=async e=>{e.preventDefault();let {error}=await sb.auth.signInWithPassword({email:$('emailInput').value,password:$('passwordInput').value});if(error)$('authError').textContent=error.message;else{let {data:{user:u}}=await sb.auth.getUser();login(u)}};$('signupBtn').onclick=async()=>{let {error}=await sb.auth.signUp({email:$('emailInput').value,password:$('passwordInput').value});$('authError').textContent=error?'注册失败：'+error.message:'注册成功，请验证邮箱后登录。'};$('logoutBtn').onclick=()=>sb.auth.signOut().then(()=>location.reload());$('prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);calendar()};$('nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);calendar()};$('todayBtn').onclick=()=>{selected=new Date();selected.setHours(0,0,0,0);month=new Date(selected.getFullYear(),selected.getMonth(),1);render()};$('saveBtn').onclick=()=>{let r=rec();r.note=$('noteInput').value;save(r)};$('uploadBtn').onclick=()=>$('photoInput').click();$('photoInput').onchange=e=>upload(e.target.files);start();
